server:
  port: 8004
  servlet:
    context-path: "/mq"

spring:
  application:
    name: train-mq-service
  profiles:
    active: prod
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/train_business?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: train
    password: 258079


# ========================mybatis===================
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.anlper.train.entities
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    cn.anlper.train.mapper: trace


mq:
  endpoint: localhost:8081
  sell-ticket-topic: TicketOrderService
  sell-ticket-consumer-group: BuyTicketConsumerGroup