server:
  port: 8001
  servlet:
    context-path: "/member"

spring:
  application:
    name: train-member-service
  profiles:
    active: prod
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/train_member?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: train
    password: 258079

config:
  info: hello nacos

# ========================mybatis===================
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.anlper.train.entities
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    cn.anlper.train.mapper: trace

#seata:
#  tx-service-group: train-group
#  config:
#    # support: nacos 、 consul 、 apollo 、 zk  、 etcd3
#    type: nacos
#    nacos:
#      server-addr: 127.0.0.1:8848
#      namespace: train
#      group: SEATA_GROUP
#      context-path:
#      ##if use MSE Nacos with auth, mutex with username/password attribute
#      #access-key:
#      #secret-key:
#      data-id: seataServer.yaml
#  registry:
#    # support: nacos 、 eureka 、 redis 、 zk  、 consul 、 etcd3 、 sofa
#    type: nacos
#    preferred-networks: 30.240.*
#    nacos:
#      application: seata-server
#      server-addr: 127.0.0.1:8848
#      group: SEATA_GROUP
#      namespace: train
#      cluster: default