GET http://localhost:8000/business/business/hello
token: {{token}}

###
GET http://localhost:8000/business/admin/station/query-list?page=1&size=2

#mobile = 112553423

###

POST http://localhost:8000/business/admin/train/save
Content-Type: application/json

{
  "code": "1232",
  "type": "1",
  "start": "南昌西",
  "startPinyin": "NCX",
  "startTime": "2021-03-12 12:23:00",
  "end": "北京北",
  "endPinyin": "BJB",
  "endTime": "2021-03-13 12:23:00"
}
###

POST http://localhost:8000/member/member/login
Content-Type: application/json

{
  "mobile": "13970414458",
  "code": "8888"
}

> {%
client.log(JSON.stringify(response.body))
client.log(JSON.stringify(response.body.content.token))
client.global.set("token", response.body.content.token)
%}
