POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "name": "test",
  "idCard": "121231",
  "type": "1"
}

###

GET http://localhost:8000/member/passenger/query-list?page=1&size=10
Accept: application/json
token: {{token}}

###

POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "id": "445516490079342592",
  "memberId": "444871275014393856",
  "name": "test111",
  "idCard": "121231",
  "type": "1"
}

###

DELETE http://localhost:8000/member/passenger/delete/445566896843132928
token: {{token}}