server:
  port: 8000

spring:
  application:
    name: train-gateway-service
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id: member
          uri: lb://train-member-service
          predicates:
            - Path=/member/**
        - id: business
          uri: lb://train-business-service
          predicates:
            - Path=/business/**
        - id: batch
          uri: lb://train-batch-service
          predicates:
            - Path=/batch/**
        - id: mq
          uri: lb://train-mq-service
          predicates:
            - Path=/mq/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - '*'
            allowedHeaders:
              - '*'
            allowedMethods:
              - '*'
            allowCredentials: true
            maxAge: 3600