server:
  port: 8000
spring:
  cloud:
    gateway:
      routes:
        - id: member
          uri: http://localhost:8001
          predicates:
            - Path=/member/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - '*'
            allowedHeaders:
              - '*'
            allowedMethods:
              - '*'
            allowCredentials: true
            maxAge: 3600