server:
  port: 8000
spring:
  cloud:
    gateway:
      routes:
        - id: member
          uri: http://localhost:8001
          predicates:
            - Path=/member/**
        - id: business
          uri: http://localhost:8002
          predicates:
            - Path=/business/**
        - id: batch
          uri: http://localhost:8003
          predicates:
            - Path=/batch/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - '*'
            allowedHeaders:
              - '*'
            allowedMethods:
              - '*'
            allowCredentials: true
            maxAge: 3600