server:
  port: 8002
  servlet:
    context-path: "/business"

spring:
  application:
    name: train-business-service
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.196.247.67/train_business?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: train
    password: 258079
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: "GMT+8"
  data:
    redis:
      host: 121.196.247.67
      port: 6379
      password: 258079
  cache:
    type: redis
    redis:
      use-key-prefix: true
      key-prefix: train_cache_
#      cache-null-values: false
      time-to-live: 30s

# ========================mybatis===================
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.anlper.train.entities
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    cn.anlper.train.mapper: trace

seata:
  tx-service-group: train-group # 事务组名称
  service:
    vgroup-mapping:
      train-group: default # 事务组和seata集群关联
    grouplist:
      default: localhost:8091 # seata集群对应的机器