spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.195.114.134/train_business?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: train
    password: 258079

  data:
    redis:
      host: 121.195.114.134
      port: 6379

mq:
  endpoint: 121.195.114.134:8081
  sell-ticket-topic: TicketOrderService